{% set name = "flufl.lock" %}
{% set version = "6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fc748ee609ec864b4838ef649dbd1170fa79deb0c213c2fd51151bee6a7fc242

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - atpublic
    - pip
    - python >=3.0
  run:
    - atpublic
    - python >=3.0

test:
  imports:
    - flufl
    - flufl.lock
    - flufl.lock.docs
    - flufl.lock.testing
    - flufl.lock.tests

about:
  home: https://flufllock.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: NFS-safe file locking with timeouts for POSIX systems.
  doc_url: https://flufllock.readthedocs.io
  dev_url: https://gitlab.com/warsaw/flufl.lock

extra:
  recipe-maintainers:
    - johanneskoester
    - efiop
