travis:
  secure:
    BINSTAR_TOKEN: E45neZmyVXTr6rrSp9PMvTp0u9FQVY9LBYx0RNUZaczosFS0Z9vX5m5UxM1iNLzsVrvA8pFCMXLQjlrDOBUM3XqEr5NtrD7g3XHSYqAj437kzjDjfNXHfSRKAi0Z8Ffmae7oszokjyNfL+lIQMIDVFEYISa4wTp/m7xMZWbQPre6OE2qDtwgDkjHfmL/OK99HkGt43nZCDgRVBLXUGJlQdNLChTjv7jtxQXYfuzwbVDvoaYj5YyyQomxxg+Nncm0F9TtckFIFZdOCTFyQYtNKdF3bXG88iG9zRBMlxLRtBWOkr33LE1rN1DNWgAxLtbxIB4EU3+BuJ6vnrBvHsxS60/s32g3Ybd3uoFGi+/X0JcywOnPxBCxIGehlQY250K1TAH1PTB2Te4OJXYohbBB2v28a5zbGRilyapUf8Fcw6mvPsRwFUVufqvZ7QAWvh0qf7VP7RS7mBO9lOlYG6HFKpdJacefAfFX2qhENh0c8mEbzMQ1/DYQNndc6Lt0C6+ziI6T8llQYEwClD4qHeRYQVv3i0cpvODOgCJQcLiZZL07gtRwuPUXU0jgxicJLh+Y4rSwqdAXlSIrPN/qJNvPvT+3zs1hILo6N2M0KZZlVbbBrXbCUhOvqDhO2e3Rem83bOkl7SroAPoSwiQeK+avggyD2V/fQDmgNFIIFTU3TM4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
